# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inventaire.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(505, 259)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, -60, 511, 441))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("inventaire.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pokemon_1 = QtWidgets.QLabel(Form)
        self.pokemon_1.setGeometry(QtCore.QRect(320, 50, 61, 51))
        self.pokemon_1.setText("")
        self.pokemon_1.setPixmap(QtGui.QPixmap("image tiles/pokemon_Combat/front/9.png"))
        self.pokemon_1.setScaledContents(True)
        self.pokemon_1.setObjectName("pokemon_1")
        self.pokemon_2 = QtWidgets.QLabel(Form)
        self.pokemon_2.setGeometry(QtCore.QRect(420, 50, 61, 51))
        self.pokemon_2.setText("")
        self.pokemon_2.setPixmap(QtGui.QPixmap("image tiles/pokemon_Combat/front/9.png"))
        self.pokemon_2.setScaledContents(True)
        self.pokemon_2.setObjectName("pokemon_2")
        self.pokemon_3 = QtWidgets.QLabel(Form)
        self.pokemon_3.setGeometry(QtCore.QRect(320, 120, 61, 51))
        self.pokemon_3.setText("")
        self.pokemon_3.setPixmap(QtGui.QPixmap("image tiles/pokemon_Combat/front/9.png"))
        self.pokemon_3.setScaledContents(True)
        self.pokemon_3.setObjectName("pokemon_3")
        self.pokemon_4 = QtWidgets.QLabel(Form)
        self.pokemon_4.setGeometry(QtCore.QRect(420, 120, 61, 51))
        self.pokemon_4.setText("")
        self.pokemon_4.setPixmap(QtGui.QPixmap("image tiles/pokemon_Combat/front/9.png"))
        self.pokemon_4.setScaledContents(True)
        self.pokemon_4.setObjectName("pokemon_4")
        self.pokemon_5 = QtWidgets.QLabel(Form)
        self.pokemon_5.setGeometry(QtCore.QRect(320, 190, 61, 51))
        self.pokemon_5.setText("")
        self.pokemon_5.setPixmap(QtGui.QPixmap("image tiles/pokemon_Combat/front/9.png"))
        self.pokemon_5.setScaledContents(True)
        self.pokemon_5.setObjectName("pokemon_5")
        self.pokemon_6 = QtWidgets.QLabel(Form)
        self.pokemon_6.setGeometry(QtCore.QRect(420, 190, 61, 51))
        self.pokemon_6.setText("")
        self.pokemon_6.setPixmap(QtGui.QPixmap("image tiles/pokemon_Combat/front/9.png"))
        self.pokemon_6.setScaledContents(True)
        self.pokemon_6.setObjectName("pokemon_6")
        self.pokemon_1_BIG = QtWidgets.QLabel(Form)
        self.pokemon_1_BIG.setGeometry(QtCore.QRect(50, 60, 161, 161))
        self.pokemon_1_BIG.setText("")
        self.pokemon_1_BIG.setPixmap(QtGui.QPixmap("image tiles/pokemon_Combat/front/9.png"))
        self.pokemon_1_BIG.setScaledContents(True)
        self.pokemon_1_BIG.setObjectName("pokemon_1_BIG")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
