# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inventaire.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form2(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(505, 259)
        self.fond = QtWidgets.QLabel(Form)
        self.fond.setGeometry(QtCore.QRect(0, -60, 511, 441))
        self.fond.setText("")
        self.fond.setPixmap(QtGui.QPixmap("../../../Downloads/Untitled design (11).png"))
        self.fond.setScaledContents(True)
        self.fond.setObjectName("fond")
        self.pok_pv_1 = QtWidgets.QLabel(Form)
        self.pok_pv_1.setGeometry(QtCore.QRect(309, 80, 71, 20))
        self.pok_pv_1.setObjectName("pok_pv_1")
        self.pok_pv_2 = QtWidgets.QLabel(Form)
        self.pok_pv_2.setGeometry(QtCore.QRect(420, 80, 60, 16))
        self.pok_pv_2.setObjectName("pok_pv_2")
        self.pok_pv_3 = QtWidgets.QLabel(Form)
        self.pok_pv_3.setGeometry(QtCore.QRect(310, 160, 60, 16))
        self.pok_pv_3.setObjectName("pok_pv_3")
        self.pok_pv_4 = QtWidgets.QLabel(Form)
        self.pok_pv_4.setGeometry(QtCore.QRect(420, 160, 60, 16))
        self.pok_pv_4.setObjectName("pok_pv_4")
        self.pok_pv_5 = QtWidgets.QLabel(Form)
        self.pok_pv_5.setGeometry(QtCore.QRect(310, 230, 60, 16))
        self.pok_pv_5.setObjectName("pok_pv_5")
        self.pok_pv_6 = QtWidgets.QLabel(Form)
        self.pok_pv_6.setGeometry(QtCore.QRect(420, 230, 60, 16))
        self.pok_pv_6.setObjectName("pok_pv_6")
        self.poke_img_1 = QtWidgets.QLabel(Form)
        self.poke_img_1.setGeometry(QtCore.QRect(310, 40, 71, 61))
        self.poke_img_1.setObjectName("poke_img_1")
        self.poke_img_2 = QtWidgets.QLabel(Form)
        self.poke_img_2.setGeometry(QtCore.QRect(420, 40, 71, 61))
        self.poke_img_2.setObjectName("poke_img_2")
        self.poke_img_3 = QtWidgets.QLabel(Form)
        self.poke_img_3.setGeometry(QtCore.QRect(310, 120, 71, 61))
        self.poke_img_3.setObjectName("poke_img_3")
        self.poke_img_4 = QtWidgets.QLabel(Form)
        self.poke_img_4.setGeometry(QtCore.QRect(420, 110, 71, 61))
        self.poke_img_4.setObjectName("poke_img_4")
        self.poke_img_5 = QtWidgets.QLabel(Form)
        self.poke_img_5.setGeometry(QtCore.QRect(310, 190, 71, 61))
        self.poke_img_5.setObjectName("poke_img_5")
        self.poke_img_6 = QtWidgets.QLabel(Form)
        self.poke_img_6.setGeometry(QtCore.QRect(410, 190, 71, 61))
        self.poke_img_6.setObjectName("poke_img_6")
        self.fond.raise_()
        self.poke_img_1.raise_()
        self.poke_img_2.raise_()
        self.poke_img_3.raise_()
        self.poke_img_4.raise_()
        self.poke_img_5.raise_()
        self.poke_img_6.raise_()
        self.pok_pv_3.raise_()
        self.pok_pv_4.raise_()
        self.pok_pv_1.raise_()
        self.pok_pv_5.raise_()
        self.pok_pv_2.raise_()
        self.pok_pv_6.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pok_pv_1.setText(_translate("Form", "TextLabel"))
        self.pok_pv_2.setText(_translate("Form", "TextLabel"))
        self.pok_pv_3.setText(_translate("Form", "TextLabel"))
        self.pok_pv_4.setText(_translate("Form", "TextLabel"))
        self.pok_pv_5.setText(_translate("Form", "TextLabel"))
        self.pok_pv_6.setText(_translate("Form", "TextLabel"))
        self.poke_img_1.setText(_translate("Form", "TextLabel"))
        self.poke_img_2.setText(_translate("Form", "TextLabel"))
        self.poke_img_3.setText(_translate("Form", "TextLabel"))
        self.poke_img_4.setText(_translate("Form", "TextLabel"))
        self.poke_img_5.setText(_translate("Form", "TextLabel"))
        self.poke_img_6.setText(_translate("Form", "TextLabel"))
