# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first_connection.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import json

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(741, 484)
        self.labelTitre = QtWidgets.QLabel(Form)
        self.labelTitre.setGeometry(QtCore.QRect(160, 50, 561, 151))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.labelTitre.setFont(font)
        self.labelTitre.setObjectName("labelTitre")
        self.labelID = QtWidgets.QLabel(Form)
        self.labelID.setGeometry(QtCore.QRect(130, 200, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        
        self.labelID.setFont(font)
        self.labelID.setObjectName("labelID")
        self.labelPassword = QtWidgets.QLabel(Form)
        self.labelPassword.setGeometry(QtCore.QRect(100, 320, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelPassword.setFont(font)
        self.labelPassword.setObjectName("labelPassword")
        self.lineEditID = QtWidgets.QLineEdit(Form)
        self.lineEditID.setGeometry(QtCore.QRect(210, 200, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEditID.setFont(font)
        self.lineEditID.setObjectName("lineEditID")
        self.lineEditPassword = QtWidgets.QLineEdit(Form)
        self.lineEditPassword.setGeometry(QtCore.QRect(210, 320, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEditPassword.setFont(font)
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(330, 400, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labelTitre.setText(_translate("Form", "PREMIERE CONNECTION"))
        self.labelID.setText(_translate("Form", "ID :"))
        self.labelPassword.setText(_translate("Form", "Password :"))
        self.pushButton.setText(_translate("Form", "Valider"))
        
        
class FirstConnection(Ui_Form):
    def __init__(self,parent=None):
        super().__init__()
        self.setupUi(parent)
        
        # Connecter le bouton de connexion à la fonction de vérification
        self.pushButton.clicked.connect(self.verifyAndRegister)

    def verifyAndRegister(self):
        # Récupérer le nom d'utilisateur et le mot de passe entrés par l'utilisateur
        ID = self.lineEditID.text()
        password = self.lineEditPassword.text()

        # Vérifier si l'utilisateur a déjà été enregistré
        if self.checkUsername(ID):
            print("ID already exists. Please choose another username.")
            return

        # Enregistrer les informations d'identification dans un fichier JSON
        self.registerNewUser(ID, password)
        print("New user registered successfully.")

    def checkUsername(self, ID):
        # Vérifier si le nom d'utilisateur existe déjà dans le fichier JSON
        with open("data_user.json", "r") as file:
            users = json.load(file)
            if ID in users:
                return True
        return False

    def registerNewUser(self, ID, password):
        # Enregistrer les nouvelles informations d'identification dans le fichier JSON
        with open("data_user.json", "r") as file:
            users = json.load(file)
        users[ID] = password
        with open("data_user.json", "w") as file:
            json.dump(users, file)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    app.setQuitOnLastWindowClosed(True)
    ui = FirstConnection(Form)
    Form.show()
    sys.exit(app.exec_())
