# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_gagner.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QMovie
from PyQt5.QtCore import *
import os

fond_ecran =  os.path.join(os.path.dirname(__file__),'image', 'pokeball.gif')


class Ui_Win(object):
    def setupUi(self, Win):
        Win.setObjectName("Win")
        Win.resize(276, 215)
        
        #Ajouter un gif de fond
        self.labelpokeball = QtWidgets.QLabel(Win)
        self.labelpokeball.setGeometry(QtCore.QRect(0, 0, 276, 215))
        self.labelpokeball.setText("")
        self.movie = QMovie(fond_ecran) #pour faire animer le gif
        self.labelpokeball.setMovie(self.movie)
        self.movie.start() # démarrer le gif
        # Redimensionnez le GIF à la taille du QLabel
        self.movie.setScaledSize(QSize().scaled(270, 270, Qt.KeepAspectRatio))
        
        
        self.pushButton_capture = QtWidgets.QPushButton(Win)
        self.pushButton_capture.setGeometry(QtCore.QRect(70, 40, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_capture.setFont(font)
        self.pushButton_capture.setObjectName("pushButton_capture")
        # Définir la couleur de fond du QPushButton
        self.pushButton_capture.setStyleSheet("background-color: white")
        
        
        self.pushButton_flee = QtWidgets.QPushButton(Win)
        self.pushButton_flee.setGeometry(QtCore.QRect(70, 120, 131, 51))
        # Définir la couleur de fond du QPushButton
        self.pushButton_flee.setStyleSheet("background-color: white")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_flee.setFont(font)
        self.pushButton_flee.setObjectName("pushButton_flee")

        self.retranslateUi(Win)
        QtCore.QMetaObject.connectSlotsByName(Win)

    def retranslateUi(self, Win):
        _translate = QtCore.QCoreApplication.translate
        Win.setWindowTitle(_translate("Win", "Win"))
        self.pushButton_capture.setText(_translate("Win", "CAPTURE"))
        self.pushButton_flee.setText(_translate("Win", "LEAVE"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Win = QtWidgets.QWidget()
    ui = Ui_Win()
    ui.setupUi(Win)
    Win.show()
    app.setQuitOnLastWindowClosed(True)
    sys.exit(app.exec_())
