# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pokedex.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os

#importer l'image du pokedex
pokedex = os.path.join(os.path.dirname(__file__), 'image', 'pokedex.jpg')



class Ui_FormPokedex(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(439, 636)
        self.labelpokedex = QtWidgets.QLabel(Form)
        self.labelpokedex.setGeometry(QtCore.QRect(10, 10, 421, 611))
        self.labelpokedex.setText("")
        self.labelpokedex.setPixmap(QtGui.QPixmap(pokedex))
        self.labelpokedex.setScaledContents(True)
        self.labelpokedex.setObjectName("labelpokedex")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(50, 120, 331, 311))
        self.tabWidget.setAccessibleName("")
        self.tabWidget.setObjectName("tabWidget")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.listWidgetPokemon = QtWidgets.QListWidget(self.widget)
        self.listWidgetPokemon.setGeometry(QtCore.QRect(0, 0, 341, 291))
        self.listWidgetPokemon.setObjectName("listWidgetPokemon")
        item = QtWidgets.QListWidgetItem()
        self.listWidgetPokemon.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidgetPokemon.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidgetPokemon.addItem(item)
        self.tabWidget.addTab(self.widget, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.listWidgetMesPokemon = QtWidgets.QListWidget(self.tab_2)
        self.listWidgetMesPokemon.setGeometry(QtCore.QRect(0, 0, 341, 301))
        self.listWidgetMesPokemon.setObjectName("listWidgetMesPokemon")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)
        

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Pokedex"))
        __sortingEnabled = self.listWidgetPokemon.isSortingEnabled()
        self.listWidgetPokemon.setSortingEnabled(False)
        item = self.listWidgetPokemon.item(0)
        item.setText(_translate("Form", "Bulbasaur"))
        item = self.listWidgetPokemon.item(1)
        item.setText(_translate("Form", "Charmander"))
        item = self.listWidgetPokemon.item(2)
        item.setText(_translate("Form", "Squirtle"))
        self.listWidgetPokemon.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("Form", "Pokemon"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Mes Pokemons"))
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_Pokedex = QtWidgets.QWidget()
    app.setQuitOnLastWindowClosed(True)
    ui_pokedex = Ui_FormPokedex()
    ui_pokedex.setupUi(Form_Pokedex)
    Form_Pokedex.show()
    sys.exit(app.exec_())
